### ISSUE TITLE
Follow symlinks/hardlinks?

### ISSUE THREAD

**Issue by deepfriedmind** [ngovil21/Plex-Cleaner#11]
I run a script which scans my download folder and creates symlinks/hardlinks with proper folder/naming structure for Plex, while allowing the original files to keep seeding. Is it possible to have the script follow the links and delete the original files too?

**Comment by randybruder** [comment]
Why not reverse your script? (Move the source file to Plex structure, create symlink/hardlink with the original file name for seeding.)

**Comment by deepfriedmind** [comment]
Sure, I could do that but I don't see how that would cause both files to be removed..?

**Comment by randybruder** [comment]
Yeah, you're right, you'd still have to manually clear out the symlinks/hardlinks.

**Comment by ngovil21** [comment]
My concern with following links would be deleting files before they are completely seeded, which could affect someone's ratio on private trackers. I think the best way would be to create a hardlink and have the torrent client delete torrents when it's done and have PlexCleaner delete it's file when it's done. If a file has been hardlinked, the file won't actually be deleted until both hardlinks are deleted. This way the torrent files and Plex files are managed separately.
