### ISSUE TITLE
ssl support

### ISSUE THREAD

**Issue by M0UL** [ngovil21/Plex-Cleaner#14]
this a great script for cleaning plex. but the only thing missing is ssl.

**Comment by ngovil21** [comment]
SSL should work. Just use `https` for the plex IP.

The script is meant to be run locally on the Plex Server so it shouldn't be necessary.

**Comment by M0UL** [comment]
i cant get it to work.

**Comment by ngovil21** [comment]
What python version are you using, which OS, and what is the error in the log?

**Comment by M0UL** [comment]
i am using python 2.7 on a synology.  there no errors in the log. it is just saying  zero files found.

**Comment by ngovil21** [comment]
Ok so after looking at it myself, it looks like the ssl certificate plex users is not valid on the localhost. Not sure if Plex handles this through a proxy or something, but it fails the SSL verification. I can disable SSL verification to make it work, but this makes the script open to unsecure man in the middle attacks which I think is worse. The script is designed to be run in a local network, so for now and probably for the future, SSL is not supported.

If you want to know how to allow unverified ssl networks in the code I will provide you the information, but won't be adding this in the main branch.
