### ISSUE TITLE
Keep Folder Structure

### ISSUE THREAD

**Issue by a214n** [ngovil21/Plex-Cleaner#15]
Is it possible to keep current folder structure when moving files? Right now I have it to move but it dumps all files into the default location. 
Example Currently : 
/data/plex/Movies/Movie Title.mp4
/data/plex/Movies/Movie Title 2.mp4
Wanting: 
/data/plex/Movies/Movie (year)/Movie Title.mp4
/data/plex/Movies/Movie 2 (year)/Movie Title 2.mp4

**Comment by ngovil21** [comment]
Sorry I don't think I will be adding this, as there is no good way of knowing what the base directory is. Do you use /data/plex/Movies or /data/plex or /data? The Plex library can have multiple root directories so there is added complexity. If you think of a way to solve this, I can look into it.

**Comment by Dreded** [comment]
would also love to see this
