### ISSUE TITLE
Error When Processing Foreign Characters

### ISSUE THREAD

**Issue by Dreded** [ngovil21/Plex-Cleaner#17]
Seems that the script doesn't properly handle characters with accent marks such as Pokémon(probably related to my other issue)

```
Pok?mon - S01xE001 - Pok?mon! I Choose You! | Viewed: 1 | Days Since Last Viewed: 68 | On Deck: False
Cannot print message

Pok?mon - S01xE002 - Pok?mon Emergency! | Viewed: 1 | Days Since Last Viewed: 68 | On Deck: False
Cannot print message
```

**Comment by ngovil21** [comment]
Can you try running with python3? 

Can you verify if the files are actually processed by navigating to the folder? The terminal window isn't able to display non-ASCII characters so the message isn't printed, but the file may still be processed by the script.

**Comment by Dreded** [comment]
so with python3 it fails completely and a bit sooner i believe the character there is a apostrophe also with the python2 i had it set to move and it did not move any of the pokemon episodes

```
Family Guy - S14xE006 - Peter?s Sister | Viewed: 1 | Days Since Last Viewed: 91 | On Deck: False
Traceback (most recent call last):
  File "./PlexCleaner.py", line 946, in <module>
    changed += checkShow(DirectoryNode)
  File "./PlexCleaner.py", line 751, in checkShow
    location=show_settings['location']):
  File "./PlexCleaner.py", line 363, in performAction
    if not os.path.isfile(file):
  File "/usr/local/lib/python3.4/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 40: ordinal not in range(128)
```

**Comment by clara-j** [comment]
Was having this issue also.  I looked online and added this right after the "import sys" line and it seems to have fixed the issue for me.

import sys
**reload(sys)
sys.setdefaultencoding("utf-8")**

Reference to stackoverflow page where I found the solution
http://stackoverflow.com/questions/9644099/python-ascii-codec-cant-decode-byte

**Comment by gonecrazy25** [comment]
I can confirm adding clara-j's solution above solved the problem for me as well, on an ' and a ñ character.

**Comment by orenwolf** [comment]
Same issue, and the fix listed here corrected it as well.

**Comment by KruyKaze** [comment]
Has this fix been merged then? Thanks

**Comment by M0UL** [comment]
i dont think this is working even on the latest dev version

**Comment by shibdib** [comment]
https://github.com/ngovil21/Plex-Cleaner/pull/27

**Comment by ngovil21** [comment]
use command line option `--reload_encoding` to use this fix.

**Comment by maxrogers** [comment]
Trying to use command line option: `--reload_encoding`

However, I get:
`PlexCleaner.py: error: argument --reload_encoding/-reload_encoding/--reload/-reload: expected one argument`

Do I need to add another argument of some sort?

**Comment by ngovil21** [comment]
sorry forgot to set it as a boolean argument. Just pushed a fix. Thanks for catching it.

**Comment by maxrogers** [comment]
Thank you! It works great now
