### ISSUE TITLE
Doesn't support unicode

### ISSUE THREAD

**Issue by Dids** [ngovil21/Plex-Cleaner#2]
Seems like the script doesn't like unicode/UTF-8 in filenames, which otherwise seem to work okay.

```
[NOT FOUND] S:\Welcome to Sweden (2014)\Welcome.to.Sweden.2014.S02E10.Sexy.Dancing.Br├Âllopet.mkv
```

**Comment by ngovil21** [comment]
Which version of python are you using?

**Comment by Dids** [comment]
2.7.10 and that is the actual path. I'm using mapped network drives.

**Comment by ngovil21** [comment]
Ok I just wanted to see if the file name is correct as it is on your file system. On IMDB the name seems that it should be Sexy Dancing/Bröllopet, the o with two dots over it, but  I see Sexy.Dancing.Br├Âllopet.mkv, with some other weird characters.

I don't think unicode works as well on Python 2, could you try running it with Python 3?

**Comment by Dids** [comment]
Seems to be working with Python 3.
