### ISSUE TITLE
Do not have the token for [username]

### ISSUE THREAD

**Issue by wilsonic** [ngovil21/Plex-Cleaner#20]
I'm trying to set this up for the first time and I'm using Show Preferences with specific homeUsers but everytime I run the script it says 

`Do not have the token for [username]. Please check spelling or report error on forums.`

I've checked with this particular user and they have set all referenced episodes to watched. Only thing I noticed was that his username has capital letters whereas the error has it all listed in lowercase.

Here's my conf file

`{
  "Host": "ipaddress",
  "Port": "32400",
  "SectionList": [2],
  "IgnoreSections": [],
  "LogFile": "cleaner.log",
  "trigger_rescan": false,
  "Token": "api",
  "Username": "",
  "Password": "",
  "Shared": false,
  "DeviceName": "devicename",
  "RemoteMount": "",
  "LocalMount": "",
  "plex_delete": false,
  "similar_files": true,
  "cleanup_movie_folders": false,
  "minimum_folder_size": 30,
  "default_episodes": 0,
  "default_minDays": 0,
  "default_maxDays": 60,
  "default_action": "keep",
  "default_watched": false,
  "default_progressAsWatched": 0,
  "default_location": "",
  "default_onDeck": true,
  "default_homeUsers": "",
  "default_ignoreFolders": [],
  "ShowPreferences": {
    "@Midnight": {
      "minDays": 15,
      "maxDays": 30,
      "onDeck": true,
      "homeUsers": "UserName",
      "episodes": 5,
      "action": "delete",
      "watched": true
    },
    "Show Preferences": {}
  },
  "MoviePreferences": {},
  "Profiles": {},
  "Version": 1.92
}
`

**Comment by ngovil21** [comment]
The script checks all lowercase to avoid case errors. I just want to confirm that the user is a Home User and not a Shared User. Home users are users you can instantly switch to from the menu. Shared Users are not supported.

If it is a home user, is there a pin? I have not tested the script with pins.

**Comment by ngovil21** [comment]
No there aren't any plans to support Shared Users. It would require getting the shared users Token or usernames and passwords.

No new features are planned, I mostly only work on bugs.

**Comment by wilsonic** [comment]
Ok, no worries.
