### ISSUE TITLE
Notifications of some sort? Email maybe?

### ISSUE THREAD

**Issue by m1lkman** [ngovil21/Plex-Cleaner#21]
How about a simple email notification or error or to notify of what's been deleted for those of us that have this script scheduled?

**Comment by ngovil21** [comment]
I am no longer adding new features to the script, but I will accept a pull request.

**Comment by jfreak53** [comment]
@ngovil21 does this mean you are discontinuing dev of this script all together? Just curious :) thanks!

**Comment by ngovil21** [comment]
@jfreak53 I am maintaining the script for bugs, but not adding new features. If someone would like to take over and fork it, they can.

**Comment by stevenflesch** [comment]
I just submitted a pull request to the development branch with the ability to email the log contents.  Thanks for maintaining this script!

**Comment by ngovil21** [comment]
Added in 7f69686379e2747e2dbfb3ef6981c10394ecb6ab
