### ISSUE TITLE
move to NAS

### ISSUE THREAD

**Issue by phairplay** [ngovil21/Plex-Cleaner#25]
hi,
i've just come across your scripts and i think its great. could i please request one change 
there are certain shows i watch and move to my NAS to keep the rest i watch and delete.

i set up a shows in the ShowPreferences section and added the nas location yet it doesnt move anything.

could this please be added?

**Comment by ngovil21** [comment]
Did you set the action to "move"? Could I see what the log and your config looks like? You can email them to me at ngovil21@gmail.com.

**Comment by phairplay** [comment]
when i add a file log location (pointed at c:\Plex-cleaner and set to overwrite i get the following error

```
C:\Users\User>python C:\Plex-Cleaner\plexCleaner.py
Loading config file: C:\Plex-Cleaner\Cleaner.conf
Traceback (most recent call last):
  File "C:\Plex-Cleaner\plexCleaner.py", line 880, in <module>
    logging.basicConfig(filename=Settings['LogFile'], filemode=filemode, level=logging.DEBUG)
  File "C:\Python27\lib\logging\__init__.py", line 1540, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "C:\Python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: u'C:\\Plex-Cleaner'
```



if i pick a location on my pc it works fine, yet when i use 
\\home-server\\Shows\\TV Shows\\Arrow it fails and i get the below 

```
Arrow - S05xE007 - Vigilante | Viewed: 1 | Days Since Last Viewed: 0 | On Deck: False
Finding files similar to: C:\Users\User\Downloads\New TV Shows\Arrow\Arrow - S05E07 - Vigilante HDTV-720p*
Error moving file: [Errno 2] No such file or directory: u'\\home-server\\Shows\\TV Shows\\Arrow'
```

**Comment by ngovil21** [comment]
Ok so for your setup, the Plex Server is a Windows machine?

You will need to setup a Mount point that has a drive letter that mounts to a folder on the NAS drive. Then use the location relative to the mount point. You will also need to make sure permissions are set up correctly so that the script can write to the NAS.

**Comment by phairplay** [comment]
okay thanks for the quick reponse
