### ISSUE TITLE
changed hadrdrive now choose. section skips

### ISSUE THREAD

**Issue by phairplay** [ngovil21/Plex-Cleaner#26]
hi i cloned my hardrive on a ssd and everything is working expect plex cleaner which i now see the follwoing in the log

INFO:root:** Script started 12-07-2016 10:23:19PM
INFO:root:
INFO:root:----------------------------------------------------------------------------
INFO:root:                           Detected Settings
INFO:root:----------------------------------------------------------------------------
INFO:root:Host: http://127.0.0.1
INFO:root:Port: 32400
INFO:root:Section List Mode: User-defined
INFO:root:Operating on user-defined sections: 3
INFO:root:Failed to load Section 3. Skipping...
INFO:root:
INFO:root:----------------------------------------------------------------------------
INFO:root:----------------------------------------------------------------------------
INFO:root:                Summary -- Script Completed Successfully
INFO:root:----------------------------------------------------------------------------
INFO:root:
INFO:root:  Total File Count      0
INFO:root:  Kept Show Files       0
INFO:root:  On Deck Files         0
INFO:root:  Deleted Files         0
INFO:root:  Moved Files           0
INFO:root:  Copied Files          0
INFO:root:  Flagged Files         0
INFO:root:  Rescanned Sections    
INFO:root:
INFO:root:----------------------------------------------------------------------------
INFO:root:----------------------------------------------------------------------------

plex is still accessed via 127.0.0.1 
what is going wrong?

**Comment by ngovil21** [comment]
Please generate a new token for PlexCleaner, save it in the config file and try again.
