### ISSUE TITLE
Auto-running every 5 minutes on Mac

### ISSUE THREAD

**Issue by randybruder** [ngovil21/Plex-Cleaner#3]
This isn't an issue, but I've created a launch agent, to make Plex Cleaner to run automatically every 5 minutes.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.ngovil21.plexcleaner</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python</string>
        <string>/path/to/your/plexcleaner/PlexCleaner.py</string>
    </array>
    <key>StartInterval</key>
    <integer>300</integer>
</dict>
</plist>
```

save this file as `com.ngovil21.plexcleaner.plist` on your Desktop, then run in terminal:

```shell
cp ~/Desktop/com.ngovil21.plexcleaner.plist ~/Library/LaunchAgents/com.ngovil21.plexcleaner.plist
sudo chmod 0600 ~/Library/LaunchAgents/com.ngovil21.plexcleaner.plist
sudo chown root ~/Library/LaunchAgents/com.ngovil21.plexcleaner.plist
launchctl load ~/Library/LaunchAgents/com.ngovil21.plexcleaner.plist
```
In Yosemite, and greater, modifying the access permissions and changing the ownership, lines 2 and 3, are necessary. Mavericks and lower, you can leave them out.

I've adapted this from [the installation instructions for PlexPy](https://github.com/drzoidberg33/plexpy/wiki/Installation), so it's probably easy to do the same if you're on Windows or Linux.

Also, the interval is set to 300 seconds, or 5 minutes. You could change that to anything you want.

**Comment by ngovil21** [comment]
This is very nice. Would you want to add it to the Wiki instead, since its not an actual problem? You can create a new page.

**Comment by ngovil21** [comment]
I went ahead and made the wiki page from your post. Thanks for your contribution. Feel free to edit the Wiki with anything else you find helpful.

**Comment by randybruder** [comment]
Awesome. Good rewrite, thanks for make the wiki page. I went in and edited it a little to use the Markdown code highlighting.
