### ISSUE TITLE
Shared Users Not Updating Views

### ISSUE THREAD

**Issue by carnivorouz** [ngovil21/Plex-Cleaner#30]
I may have something misconfigured but I can't figure out what just yet.  I have the script running on a cron job and appending the log.  What I've noticed over several days is users are viewing movies which I confirm with PlexPy but the Days Since Viewed and Viewed values are not updating.
I have "Shared": true, set in Cleaner.conf and now 'Shared = True' set in PlexCleaner.py since the .conf wasn't doing it.
Any idea what's going wrong?

output.log
![](http://i.imgur.com/k8ZZyxZ.png)

PlexPy
![](http://i.imgur.com/n6Xg9Mm.png)

Cleaner.conf
```
{
  "Host": "192.168.1.92",
  "Port": "32400",
  "SectionList": [1],
  "IgnoreSections": [],
  "LogFile": "/mnt/Plex/Plex-Cleaner/output.log",
  "LogFileMode": "append",
  "trigger_rescan": false,
  "Token": "xxxxxxxxxxxxxxxxxxxxx",
  "Username": "",
  "Password": "",
  "Shared": true,
  "DeviceName": "",
  "RemoteMount": "",
  "LocalMount": "",
  "plex_delete": false,
  "similar_files": false,
  "cleanup_movie_folders": true,
  "minimum_folder_size": 30,
  "default_episodes": 0,
  "default_minDays": 14,
  "default_maxDays": 0,
  "default_action": "flag",
  "default_watched": true,
  "default_progressAsWatched": 0,
  "default_location": "",
  "default_onDeck": true,
  "default_homeUsers": "",
  "default_ignoreFolders": ["/mnt/Media/Movies/Archive"],
  "MoviePreferences": {
    "action": "delete",
    "location": "/mnt/Media/Movies",
    "minDays": 183,
    "onDeck": true,
    "watched": false
  },
  "Version": 1.93
}
```

**Comment by ngovil21** [comment]
The Shared option is only if you are using the token from a Shared account, it doesn't check the watch status from multiple shared accounts. Managing multiple users will only work with users in a Plex Home (the ones you can quickly switch between).

**Comment by carnivorouz** [comment]
Ah ok I misunderstood then; that is unfortunate.  Thanks for the follow-up.
