### ISSUE TITLE
Section detection not working anymore

### ISSUE THREAD

**Issue by Danelem** [ngovil21/Plex-Cleaner#32]
Since the last version (1.4.3.3433), the section detection is not working anymore. It just tells me that it failed to load section X.

Also, when you look in the address bar in Plex, the URL is not the same as it used to be. This is how it is now:  ?key=%2Flibrary%2Fsections%2F6

Looks like an URL encode issue maybe?

Any clue?

**Comment by cmivxx** [comment]
I'm having the same problem.  Plex updated something in the API.  Any help updating would be great!

**Comment by Danelem** [comment]
Yes, I think you're right, but I didn't find any documentation about changes in the API.

Anyone would have some details about these changes?

**Comment by ngovil21** [comment]
I don't think the API changed from my testing. Please try creating a new token and using that in the script.

**Comment by Danelem** [comment]
I tried a new token, I also tried to use only the username authentication. It didn't help b

**Comment by ngovil21** [comment]
Ok, please email your config file with token removed and send me the script with the `--debug` flag to ngovi21@gmail.com.

**Comment by Danelem** [comment]
Ok, I'm doing it.

Thanks a lot!

**Comment by Dids** [comment]
@Danelem So what fixed this for you?

**Comment by Danelem** [comment]
Check the credentials, and renew the token.

On Apr 16, 2017 13:48, "Pauli Jokela" <notifications@github.com<mailto:notifications@github.com>> wrote:

@Danelem<https://github.com/Danelem> So what fixed this for you?

**Comment by Dids** [comment]
Thanks! Using credentials without a token worked for me before, but somehow suddenly broke. Using the token fixed it.
