### ISSUE TITLE
Error in 1.9.4  - NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by myn** [ngovil21/Plex-Cleaner#33]
Upgraded PlexCleaner.py from 1.9.3 to 1.9.4 and now getting error:

C:\PlexCleaner>PlexCleaner.py
Traceback (most recent call last):
  File "C:\PlexCleaner\PlexCleaner.py", line 809, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by myn** [comment]
Just tested development branch 1.9.41 PlexCleaner.py which appears to have a now optional Reload command and it is working again.

**Comment by ngovil21** [comment]
ya I figured the optional command will work better. I will merge the update into the master branch soon.

**Comment by ngovil21** [comment]
Merged in 3166bfcfbd4e767481f21b9f9df3bf35e8475272
