### ISSUE TITLE
Where to save script on NAS

### ISSUE THREAD

**Issue by petrmenzel** [ngovil21/Plex-Cleaner#34]
Hi, I am using Ples on NAS.

Where to place this script? I have supposed that it could be Plug-Ins directory. But if I tried it nothing happened. Does it work like o plugin (agent)?

Thx you for explanation.

**Comment by randybruder** [comment]
This doesn't work like a plugin, but rather as a standalone Python script. I'm not sure about getting it to run on a NAS, but you could run it from a computer and point the script at the IP address of your Plex server (the NAS.) Of course that means the computer running the script would also need to be always on (for the script to run every interval you'd set up.)
