### ISSUE TITLE
[RFE] List deleted/affected files in summary

### ISSUE THREAD

**Issue by orenwolf** [ngovil21/Plex-Cleaner#35]
Hi!

First, thanks so much for PlexCleaner!

Low priority, but it'd be great to have an option to list the files that were flagged/deleted in the summary. If you have a large library, it can be cumbersome to search for affected files among hundreds of "[Keeping]" entries. :)

Again, low priority, there's always grep, but if you end up refactoring the summary someday, I'd love to see this added. Thanks again!

**Comment by ngovil21** [comment]
added 8f65fd5fb95a83ce8e2293ce494d2bdd4c7995f8
