### ISSUE TITLE
Script on htpc server on nvidia?

### ISSUE THREAD

**Issue by phairplay** [ngovil21/Plex-Cleaner#37]
Hi, 
I'm wanting to play 4K but my pc won't cope with it. Is it possible to run this script on my pc with the plex server on a nvidia shield?

All my content will remain on the PC or my NAS

Many thanks

**Comment by ngovil21** [comment]
I haven't tested it, but it should work in theory. You would need to setup the script to set `plex_delete` (might not work) to true, or you could setup the `RemoteMount` (to the top media directory on the Shield) and `LocalMount` (to the top media directory on the PC) variables.

If you test it out, let me know how it works.

**Comment by jmulvaney1** [comment]
Is there no way to run the script  on the Shield,  if it is rooted?   If so, how?
