### ISSUE TITLE
Add option to delete related subtitle (i.e. srt for example) files when show files are deleted. 

### ISSUE THREAD

**Issue by jbunselmeyer** [ngovil21/Plex-Cleaner#44]
How feasible would it be to add the ability to also deleted related subtitle files when show/episode files are deleted? 

I have subtitles automatically downloaded and Plex-Cleaner works great running daily and deleting watched episodes but I have to go in and manually delete all the subtitle files periodically. If this could be added to Plex-Cleaner that would be great.

**Comment by M0UL** [comment]
this is already possible, in the the config file. you need to set  similar_files  to true. then it will dlete your subtiles.

**Comment by jbunselmeyer** [comment]
Thanks for pointing that out, missed that when skimming through the config file. Sorry for cluttering up the issues with this. :)
