### ISSUE TITLE
Option to Exclude deleting Movied

### ISSUE THREAD

**Issue by jmulvaney1** [ngovil21/Plex-Cleaner#46]
I do not want PlexCleaner to delete movies, even if watched.  I prefer to do this manually.  So I ignore the Movie section in the scan.  But then the option to cleanup Movie Folders if under certain size is ignored.
How can I include the Movie sections in the scan, but not have PlexCleaner delete watched movies?

**Comment by ngovil21** [comment]
You should include the movie section in the scan, but set the MoviePreferences action to 'keep'. That should work. Please try it with copies of your movies in a new section.
