### ISSUE TITLE
Exclude a category

### ISSUE THREAD

**Issue by menardorama** [ngovil21/Plex-Cleaner#47]
Hi 
Your tool seems great but I wonder if it was possible to exclude a category ?

My concern is that I want to delete all the movies already seen but my kids need to watch again and again and again cartoons.

If it's possible can you explain me ?

Thanks a lot

**Comment by CriticalPoint** [comment]
What I do in this situation is I have the kids stuff in it's own folder, added to Plex under it's own 'Section', so that I can just ignore it.

You can ignore, or controversially, target specific sections in the config file.

**Comment by menardorama** [comment]
Yes I saw that, but the only thing annoying with that is that the process that "put" me the movie don't move video files based on the category...

That's why I thought to exclude a list of category

**Comment by CriticalPoint** [comment]
Oh I see, you're specifically referring to a _Plex Category_, I understand! I myself don't use them and as such, I'm afraid I can't help any further, sorry!

**Comment by menardorama** [comment]
Ok thanks I'll try to have a look if it's accessible in the API

Are you open to Pull request ?

**Comment by CriticalPoint** [comment]
ngovil21 has merged a few, so I suspect the author will be open to that 👍

**Comment by CriticalPoint** [comment]
I've just had a closer look and I found a 'NeverDelete' Collection in my Plex movies, so I definitely found a way to save them from being deleted!

**Comment by menardorama** [comment]
where did you find it ?

**Comment by CriticalPoint** [comment]
Under "Profiles" in the config.

**Comment by ngovil21** [comment]
Create a Collection in Plex and add the movies you do not want deleted to that collection. Then create a Profile in the config file with the name of the Collection with `action: 'keep'`.
