### ISSUE TITLE
Last seen episode doesnt get deleted.

### ISSUE THREAD

**Issue by nexoske** [ngovil21/Plex-Cleaner#49]
Hi,

the script works like a charm, but for some reason the last watched episode doesnt get moved or deleted.

Any Ideas?

 "default_episodes": 0,
  "default_minDays": 0,
  "default_maxDays": 0,
  "default_action": "move",
  "default_watched": true,
  "default_progressAsWatched": 1,
  "default_location": "E://delete",
  "default_onDeck": true,
  "default_homeUsers": "",

**Comment by CriticalPoint** [comment]
I get the same thing

**Comment by ngovil21** [comment]
If onDeck is marked as true, then the last watched episode doesn't get deleted so that the next episode will still show up on your on Deck. That's just how Plex works.

**Comment by nexoske** [comment]
this worked and my next episode still shows up on deck, so double win :)

2017-11-05 15:31 GMT+01:00 ngovil21 <notifications@github.com>:
