### ISSUE TITLE
Functionality Request

### ISSUE THREAD

**Issue by AndyPeepsJR** [ngovil21/Plex-Cleaner#50]
Sorry, didn't know how to send you suggestions for improving the Plex-Cleaner script. Here's what would help me:

1. Ability to retain the folder structure relative to the Library Root folder when moving or copying
2. Ability to run a command line with filename substitution after a move/copy or in place of.

The reason I ask, my cleaning process is to recode into x265 onto a slow backup drive which is picked up by my Plex server as it's Archive folders.

**Comment by ngovil21** [comment]
May look at retaining folder structure for moves and copies. Would be relative to the Plex Library, but this could be complicated because you can have multiple folders in a single Plex Library.

Unlikely to add running an additional command because that will hold up the script.

**Comment by AndyPeepsJR** [comment]
Fantastic, thank you. When you say relative to the Plex Library, do you mean relative to the Plex Library path?
