### ISSUE TITLE
Allow 'any' home user

### ISSUE THREAD

**Issue by MakoNakor** [ngovil21/Plex-Cleaner#51]
Would like the ability to specify that any home user can count as watched, currently if home_users is blank, no home users are checked at all.

**Comment by ngovil21** [comment]
I have added this in. I think it should work from my testing. If you are still interested let me know. Make sure Home Users have access to the libraries that you scan.

**Comment by MakoNakor** [comment]
Yeah, I would be glad to test it out.

**Comment by MakoNakor** [comment]
So I tried to get this working, in comparing the config, the time it took to run went from 33s to over 7 minutes until i stopped it. Examining the log, I saw a lot of 404 errors, that were not in the previous run.
[testnewconfig.log](https://github.com/ngovil21/Plex-Cleaner/files/1696323/testnewconfig.log)

**Comment by ngovil21** [comment]
If you use any, then all home users need to have access to all of the
libraries scanned by the script. I'll add more error checking to skip if it
can't be found.

**Comment by MakoNakor** [comment]
Yeah, that makes sense. I have child accounts created, so there are some shows they do not have access to.

**Comment by ngovil21** [comment]
Yes, it will now error only once if the user is unable to access the
library. This will happen for each episode in the show.
