### ISSUE TITLE
Deleting empty movie folders - minimum size

### ISSUE THREAD

**Issue by jmulvaney1** [ngovil21/Plex-Cleaner#55]
Changing the size for "minimum folder size" appears to make no difference and the script always only target folders with a minimum size of 30mb (default).  How can I increase this to 200mb?

"cleanup_movie_folders": true,
 "minimum_folder_size": 200,

**RESPONSE**
_Cleaning up orphaned folders less than 30MB in Section 3
**[Flagged]: /volume1/NAS/Movies/Alien (1979)/
Size 19813162 bytes_

**Comment by ngovil21** [comment]
Had a bug in the code that ignored the Settings. Should be fixed now. Try pulling and using those same settings.
