### ISSUE TITLE
If action is "flag" and "--show_size" OR "plex_delete" is not set, then the show is "[NOT FOUND]"

### ISSUE THREAD

**Issue by duckpuppy** [ngovil21/Plex-Cleaner#57]
```python
       if show_size and os.path.isfile(file):
           FlaggedSize += os.stat(file).st_size
       elif not Settings['plex_delete']:
           log("[NOT FOUND] " + file)
           return False
```

The above code from the flagging code seems to say "If show_size is not set AND plex_delete is not set, then log NOT FOUND".  Is that how it's supposed to work, or am I reading that wrong?

**Comment by ngovil21** [comment]
You are right. Thanks for finding that so fast.
Fixed in a6af4582b5e15e71edfc15e6f2b022d7b831465d

Also added error checking for file names that can't be decoded.
