### ISSUE TITLE
Error when running with Python3

### ISSUE THREAD

**Issue by 10of12** [ngovil21/Plex-Cleaner#67]
Hello,

i had used Plex-Cleaner for the last few months with Python2 for my tv section. Now i start using it for my movie section too. Now i have the error with foreign characters, like in Issue #17 

I tried to run it with --reload_encoding, but got the same problem.

When i try to run Plex-Cleaner with Python3, i have the error:
`
Traceback (most recent call last):
  File "/home/plex/scripts/Plex-Cleaner/PlexCleaner.py", line 190, in <module>
    from urllib.Error import HTTPError
ImportError: No module named 'urllib.Error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/plex/scripts/Plex-Cleaner/PlexCleaner.py", line 193, in <module>
    from urllib2 import HTTPError
ImportError: No module named 'urllib2'
`

python3-urllib3 is installed on my System. I use Ubuntu 16.04.

**Comment by gonecrazy25** [comment]
There is a typo in the script at least for python3 on centos.  On line 190 change:

`from urllib.Error import HTTPError`

to

`from urllib.error import HTTPError`

This seems to solve the problem.

**Comment by ngovil21** [comment]
Updated the script with this fix.

**Comment by 10of12** [comment]
Yes, it's working for me now too.
Thanks
