### ISSUE TITLE
Do not have the token for home user?

### ISSUE THREAD

**Issue by derekoharrow** [ngovil21/Plex-Cleaner#68]
I'm trying to get plex-cleaner working. It works if I just use my/admin account and token just fine, but I have other users (all homeUsers that I can switch between).

When I try to use these - e.g. "Grey's Anatomy": { "homeUsers": "me,them"} I get the error:

`[ERROR] Do not have the token for them. Please check spelling or token.`

I saw somewhere on here how to specify multiple tokens, so set this up like below:
```
"Token": {
  "me*": "mytoken...",
  "them": "theirtoken..."
}
```
But this still doesn't seem to solve the problem - it then says:
`Unauthorized to access url with token.`
How should I obtain the token for the Home Users to go into the Token section?

**Comment by ngovil21** [comment]
If you are using homeUsers, don't use the Token dictionary. Make sure that the the username is spelled correctly and try using all lowercase for the names.

**Comment by ngovil21** [comment]
Fixed a bug with home users. Please update and follow the above instructions.
