### ISSUE TITLE
400: bad request errors

### ISSUE THREAD

**Issue by hippytyre** [ngovil21/Plex-Cleaner#71]
I'm getting quite a lot of 400: bad request errors, I've tried changing plex delete to false but the errors still persist. Here's an example.

> Instinct (2018) - S01xE004 - I Heart New York | Viewed: 1 | Days Since Last Viewed: 1 | On Deck: False
Error requesting page: HTTP Error 400: Bad Request
Unable to plex delete file: /storage/MCHOKAY/shares/Shows/Instinct (2018)/Season 1/Instinct (2018) - S01E04 - I Heart New York WEBDL-720p.mkv

**Comment by ngovil21** [comment]
The script is still trying to use plex delete, check which config the script is using. Maybe you edited the wrong config file.
