### ISSUE TITLE
Episode file not getting picked up 

### ISSUE THREAD

**Issue by Veronit** [ngovil21/Plex-Cleaner#74]
I have an episode file that I can't figure out why it's not getting picked up by Plex-Cleaner.

I have executed cleaner using debug flag and noticed that debug says that the file is On Deck, even though the normal log says it is not. Plex also says that the next episode is on deck.

Log:
{'onDeck': True, 'maxDays': 0, 'minDays': 0, 'homeUsers': u'', 'episodes': 0, 'location': u'/mnt/mybook/Media/Janitor', 'action': u'flag', 'watched': True, 'progressAsWatched': 0}
Parks and Recreation - S04xE001 - I'm Leslie Knope | Viewed: 2 | Days Since Last Viewed: 107 | On Deck: False
File is on deck, not deleting
Watched status is True and compare day is 107 and deck status is False
[KEEPING] /storage/RPILATAUS/PiShare/Media/Sarjat/Parks and Recreation/Season 4/Parks and Recreation S04E01 720p WEB-DL DD5.1 H.264.mkv

**Comment by ngovil21** [comment]
It's because of how Plex tracks On Deck. An episode will be On Deck if the previous episodes has been marked as watched. If we delete the previous episode, Plex will stop tracking the metadata and your video will will not show up On Deck anymore.
