### ISSUE TITLE
What's the difference between minDays and maxDays?

### ISSUE THREAD

**Issue by Kurchunk** [ngovil21/Plex-Cleaner#75]
I have spent a lot of time looking at the code and thinking it over, but I can't figure out why there is both a min and max (or why I would set both of them) in the config file.

The main Python file explains them both the same way: _Episodes added more than
default_minDays/default_maxDays ago will be deleted._

Can I get a simpler explanation and some use examples?

**Comment by ngovil21** [comment]
`minDays` is used to delete files after they have been added a certain number of days agos, or there after they are watched a certain number of days ago, if `watched` is True.

`maxDays` only comes into use when the `episodes` tag is used. If `episodes` is set to 3 and maxDays set to 60, there will be 3 episodes saved on the server, the episodes will be deleted after they are 60 days old.

**Comment by Kurchunk** [comment]
Thanks. I think I'm understanding it now.

So `maxDays` only matters if I'm using the `episodes` tag... Does that mean `maxDays` is only for TV Shows and `minDays` is only for movies (or is it a universal setting for both Movies and Shows)?

**Comment by ngovil21** [comment]
`maxDays` only applies to TV Shows.

`minDays' applies to both TV Shows and Movies. There are options to set it separately for each one.

**Comment by Kurchunk** [comment]
I'm so late responding to this. I got distracted, but I came back to this because I lost my old config file and needed to create a new one.

This helps tremendously!
