### ISSUE TITLE
[NOT FOUND] even though the file is there

### ISSUE THREAD

**Issue by hippytyre** [ngovil21/Plex-Cleaner#77]
I get lots of these errors when I run the script even though the file is there.

Luther - S05xE002 - Episode 2 | Viewed: 1 | Days Since Last Viewed: 11 | On Deck: False
[NOT FOUND] /storage/shares/Shows/Luther/Season 5/Luther - S05E02 - Episode 2 SDTV.mkv

Could it be a permissions issue? I'm running the script as root.

Thanks

**Comment by adamwinn** [comment]
I'm seeing this too.

**Comment by adamwinn** [comment]
When I was running plex cleaner from my Mac, it would see the files on my NAS as [NOT FOUND].  They had 777 permissions and were definitely there.  Spaces in the filename didn't matter either.  When I ran plex cleaner directly on my NAS, the files were found and were deleted.

**Comment by Migz93** [comment]
Also having the same issue, don't have another machine i can run from. I tried running the script in a docker container but that gave the same error.

**Comment by adamwinn** [comment]
I think my problem was not having LocalMount and RemoteMount filled out.  I debugged this and `getLocalPath()` wasnt returning the correct path so I filled in LocalMount and RemoteMount and it worked
