### ISSUE TITLE
Ignore Folders FEATURE REQUEST

### ISSUE THREAD

**Issue by 00lex** [ngovil21/Plex-Cleaner#79]
Hi im a little bit lazy to go into the config file every time. 
Could you implement a function to ignore folders where a file eg ".cleanerignore" is? 
the idea comes from "Sub-Zero for Plex" there is this option to prevent subtitle search for some folders. 

Thanks

**Comment by MakoNakor** [comment]
I use Plex tags to accomplish this. 

```json
"Profiles":  {
  "Keep": {
    "action": "keep"
  }
}
```

Then just go into edit at the show or movie level and add a Category "Keep"

**Comment by 00lex** [comment]
But it’s easier to place a file in a folder of a new added tvshow

**Comment by ngovil21** [comment]
Added in version 1.92
